// vehicleData.ts — Static make/model/trim data
// Lazy-loaded by BookingWidget. Add new models/trims here as needed.

export const VEHICLE_MODELS: Record<string, string[]> = {
  'Acura':         ['MDX', 'NSX', 'RDX', 'TL', 'TLX', 'TSX'],
  'BMW':           ['3 Series', '5 Series', 'X3', 'X5'],
  'Cadillac':      ['CTS', 'Escalade', 'SRX'],
  'Chevrolet':     ['Avalanche', 'Camaro', 'Cavalier', 'Cobalt', 'Colorado', 'Corvette', 'Cruze', 'Equinox', 'HHR', 'Impala', 'Malibu', 'Monte Carlo', 'S-10', 'Silverado 1500', 'Silverado 2500HD', 'Silverado EV', 'Sonic', 'Spark', 'SSR', 'Suburban', 'Tahoe', 'Trailblazer', 'Traverse'],
  'Chrysler':      ['300', 'Pacifica', 'PT Cruiser', 'Sebring', 'Town & Country'],
  'Dodge':         ['Avenger', 'Caliber', 'Challenger', 'Charger', 'Dakota', 'Durango', 'Grand Caravan', 'Journey', 'Neon', 'Stealth', 'Viper'],
  'Ford':          ['Bronco', 'Bronco Sport', 'Crown Victoria', 'Edge', 'Escape', 'Excursion', 'Expedition', 'Explorer', 'F-150', 'F-250 Super Duty', 'F-350 Super Duty', 'F-Series Lightning', 'Flex', 'Focus', 'Fusion', 'Maverick', 'Mustang', 'Ranger', 'Taurus', 'Thunderbird', 'Transit'],
  'Genesis':       ['G80', 'GV70'],
  'GMC':           ['Acadia', 'Canyon', 'Envoy', 'Hummer EV', 'Sierra 1500', 'Sierra 2500HD', 'Terrain', 'Yukon'],
  'Honda':         ['Accord', 'Civic', 'CR-V', 'CR-Z', 'Element', 'Fit', 'HR-V', 'Insight', 'Odyssey', 'Passport', 'Pilot', 'Prelude', 'Ridgeline', 'S2000'],
  'Hyundai':       ['Elantra', 'Genesis', 'Ioniq 5', 'Kona', 'Palisade', 'Santa Cruz', 'Santa Fe', 'Sonata', 'Tucson', 'Veloster'],
  'Infiniti':      ['G35', 'G37', 'Q50', 'Q60', 'QX60', 'QX80'],
  'Jeep':          ['Cherokee', 'Commander', 'Compass', 'Gladiator', 'Grand Cherokee', 'Grand Wagoneer', 'Liberty', 'Patriot', 'Renegade', 'Wagoneer', 'Wrangler'],
  'Kia':           ['EV6', 'Forte', 'K5', 'Niro', 'Optima', 'Sorento', 'Soul', 'Sportage', 'Stinger', 'Telluride'],
  'Lexus':         ['ES', 'GX', 'IS', 'LX', 'RX'],
  'Lincoln':       ['MKX', 'MKZ', 'Navigator', 'Town Car'],
  'Lucid':         ['Air'],
  'Mazda':         ['CX-5', 'CX-9', 'Mazda3', 'Mazda6', 'MX-5 Miata', 'RX-7', 'RX-8', 'Tribute'],
  'Mercedes-Benz': ['C-Class', 'E-Class', 'GLE'],
  'Mercury':       ['Grand Marquis', 'Mariner', 'Milan', 'Mountaineer'],
  'Mitsubishi':    ['3000GT', 'Eclipse', 'Lancer', 'Outlander'],
  'Nissan':        ['350Z', '370Z', 'Altima', 'Armada', 'Frontier', 'GT-R', 'Maxima', 'Murano', 'Pathfinder', 'Rogue', 'Sentra', 'Titan', 'Titan XD', 'Xterra', 'Z'],
  'Oldsmobile':    ['Alero', 'Bravada', 'Intrigue'],
  'Polestar':      ['Polestar 2', 'Polestar 3'],
  'Pontiac':       ['Firebird', 'G6', 'G8', 'Grand Prix', 'Solstice', 'Vibe'],
  'Porsche':       ['911', 'Cayenne', 'Macan'],
  'RAM':           ['1500', '2500', '3500'],
  'Rivian':        ['R1S', 'R1T'],
  'Saturn':        ['Ion', 'Sky', 'Vue'],
  'Subaru':        ['Ascent', 'Baja', 'BRZ', 'Crosstrek', 'Forester', 'Impreza', 'Legacy', 'Outback', 'Tribeca', 'WRX'],
  'Tesla':         ['Cybertruck', 'Model 3', 'Model S', 'Model X', 'Model Y'],
  'Toyota':        ['4Runner', 'Avalon', 'Camry', 'Celica', 'Corolla', 'Corolla Cross', 'Echo', 'FJ Cruiser', 'GR Corolla', 'GR86', 'Highlander', 'Land Cruiser', 'Matrix', 'MR2', 'Pickup', 'Prius', 'Prius Prime', 'RAV4', 'RAV4 Prime', 'Sequoia', 'Sienna', 'Solara', 'Supra', 'T100', 'Tacoma', 'Tundra', 'Venza', 'Yaris'],
  'Volkswagen':    ['Atlas', 'Beetle', 'Golf', 'ID.4', 'Jetta', 'Passat', 'Tiguan'],
  'Volvo':         ['S60', 'S90', 'XC40', 'XC60', 'XC90'],
};

export const MAKES: string[] = Object.keys(VEHICLE_MODELS).sort();

// VEHICLE_TRIMS — common trim levels per model
// Key: "Make|Model" (uppercase). Values: display trim names.
// "Other / not listed" is appended automatically by the UI.
export const VEHICLE_TRIMS: Record<string, string[]> = {
  // Toyota
  'TOYOTA|CAMRY':         ['LE', 'SE', 'XSE', 'XLE', 'TRD', 'Hybrid LE', 'Hybrid SE', 'Hybrid XLE'],
  'TOYOTA|COROLLA':       ['L', 'LE', 'SE', 'XSE', 'XLE', 'Hybrid LE', 'Hybrid SE'],
  'TOYOTA|RAV4':          ['LE', 'XLE', 'XLE Premium', 'TRD Off-Road', 'Adventure', 'Limited', 'Prime SE', 'Prime XSE'],
  'TOYOTA|TACOMA':        ['SR', 'SR5', 'TRD Sport', 'TRD Off-Road', 'Limited', 'TRD Pro'],
  'TOYOTA|TUNDRA':        ['SR', 'SR5', 'Limited', 'Platinum', '1794 Edition', 'TRD Pro', 'Capstone'],
  'TOYOTA|HIGHLANDER':    ['LE', 'XLE', 'XSE', 'Limited', 'Platinum', 'Hybrid LE', 'Hybrid XLE', 'Hybrid Limited', 'Hybrid Platinum'],
  'TOYOTA|4RUNNER':       ['SR5', 'SR5 Premium', 'TRD Sport', 'TRD Off-Road', 'TRD Off-Road Premium', 'Limited', 'TRD Pro'],
  'TOYOTA|PRIUS':         ['L Eco', 'LE', 'XLE', 'Limited'],
  'TOYOTA|SIENNA':        ['LE', 'XLE', 'XSE', 'Limited', 'Platinum'],
  'TOYOTA|SEQUOIA':       ['SR5', 'Limited', 'Platinum', 'TRD Pro', 'Capstone'],
  'TOYOTA|AVALON':        ['XLE', 'XSE', 'Limited', 'Touring'],
  'TOYOTA|SUPRA':         ['2.0', '3.0', '3.0 Premium', 'A91-CF Edition'],
  'TOYOTA|FJ CRUISER':    ['Base'],
  'TOYOTA|VENZA':         ['LE', 'XLE', 'Limited'],
  'TOYOTA|YARIS':         ['L', 'LE', 'XLE'],
  // Honda
  'HONDA|CIVIC':          ['LX', 'Sport', 'EX', 'EX-L', 'Touring', 'Si', 'Type R'],
  'HONDA|ACCORD':         ['LX', 'Sport', 'Sport-L', 'EX-L', 'Touring', 'Hybrid Sport', 'Hybrid Touring'],
  'HONDA|CR-V':           ['LX', 'EX', 'EX-L', 'Touring', 'Hybrid Sport', 'Hybrid EX-L', 'Hybrid Touring'],
  'HONDA|PILOT':          ['LX', 'EX', 'EX-L', 'Touring', 'Elite', 'TrailSport', 'Black Edition'],
  'HONDA|ODYSSEY':        ['LX', 'EX', 'EX-L', 'Touring', 'Elite'],
  'HONDA|RIDGELINE':      ['Sport', 'RTL', 'RTL-E', 'Black Edition'],
  'HONDA|HR-V':           ['LX', 'Sport', 'EX', 'EX-L'],
  'HONDA|PASSPORT':       ['Sport', 'EX-L', 'Touring', 'Elite', 'TrailSport'],
  'HONDA|FIT':            ['LX', 'Sport', 'EX', 'EX-L'],
  'HONDA|ELEMENT':        ['LX', 'EX', 'SC'],
  'HONDA|S2000':          ['Base'],
  'HONDA|PRELUDE':        ['Base', 'Si'],
  // Ford
  'FORD|F-150':           ['Regular Cab XL', 'Regular Cab XLT', 'SuperCab XL', 'SuperCab XLT', 'SuperCab Lariat', 'SuperCrew XL', 'SuperCrew XLT', 'SuperCrew Lariat', 'SuperCrew King Ranch', 'SuperCrew Platinum', 'SuperCrew Limited', 'Raptor', 'Tremor'],
  'FORD|F-250 SUPER DUTY':['XL', 'XLT', 'Lariat', 'King Ranch', 'Platinum', 'Limited', 'Tremor'],
  'FORD|F-350 SUPER DUTY':['XL', 'XLT', 'Lariat', 'King Ranch', 'Platinum', 'Limited'],
  'FORD|ESCAPE':          ['S', 'SE', 'SEL', 'Titanium', 'Plug-In Hybrid SE', 'Plug-In Hybrid Titanium'],
  'FORD|EXPLORER':        ['Base', 'XLT', 'ST-Line', 'Timberline', 'Limited', 'ST', 'Platinum', 'King Ranch'],
  'FORD|MUSTANG':         ['EcoBoost', 'EcoBoost Premium', 'GT', 'GT Premium', 'Mach 1', 'Shelby GT500', 'Dark Horse'],
  'FORD|BRONCO':          ['Base', 'Big Bend', 'Black Diamond', 'Outer Banks', 'Badlands', 'Wildtrak', 'Everglades', 'Raptor', 'Heritage', 'Heritage Limited'],
  'FORD|RANGER':          ['XL', 'XLT', 'Lariat', 'Raptor'],
  'FORD|EXPEDITION':      ['XL', 'XLT', 'Limited', 'Timberline', 'King Ranch', 'Platinum', 'Stealth Edition'],
  'FORD|EDGE':            ['SE', 'SEL', 'ST-Line', 'Titanium', 'ST'],
  'FORD|MAVERICK':        ['XL', 'XLT', 'Lariat', 'Tremor'],
  'FORD|FUSION':          ['S', 'SE', 'SEL', 'Titanium', 'Sport', 'Hybrid SE', 'Hybrid Titanium', 'Energi SE', 'Energi Titanium'],
  'FORD|FOCUS':           ['S', 'SE', 'SEL', 'Titanium', 'ST', 'RS'],
  'FORD|TAURUS':          ['SE', 'SEL', 'Limited', 'SHO'],
  // Chevrolet
  'CHEVROLET|SILVERADO 1500': ['WT', 'Custom', 'Custom Trail Boss', 'LT', 'LT Trail Boss', 'RST', 'LTZ', 'Trail Boss', 'High Country', 'ZR2'],
  'CHEVROLET|SILVERADO 2500HD': ['WT', 'Custom', 'LT', 'LTZ', 'High Country'],
  'CHEVROLET|EQUINOX':    ['LS', 'LT', 'RS', 'Premier', 'EV 1LT', 'EV 2LT', 'EV 3LT'],
  'CHEVROLET|TRAVERSE':   ['LS', 'LT', 'RS', 'Premier', 'High Country'],
  'CHEVROLET|TAHOE':      ['LS', 'LT', 'RST', 'Z71', 'Premier', 'High Country'],
  'CHEVROLET|SUBURBAN':   ['LS', 'LT', 'RST', 'Z71', 'Premier', 'High Country'],
  'CHEVROLET|CAMARO':     ['LS', 'LT', 'LT1', 'SS', '1LE', 'ZL1'],
  'CHEVROLET|CORVETTE':   ['Stingray', 'Grand Sport', 'Z06', 'ZR1', 'E-Ray'],
  'CHEVROLET|MALIBU':     ['LS', 'RS', 'LT', 'Premier'],
  'CHEVROLET|COLORADO':   ['WT', 'LT', 'Z71', 'ZR2'],
  'CHEVROLET|TRAILBLAZER':['LS', 'LT', 'ACTIV', 'RS'],
  'CHEVROLET|IMPALA':     ['LS', 'LT', 'Premier'],
  'CHEVROLET|CRUZE':      ['LS', 'LT', 'Premier'],
  'CHEVROLET|SONIC':      ['LS', 'LT', 'Premier'],
  // GMC
  'GMC|SIERRA 1500':      ['Pro', 'SLE', 'Elevation', 'SLT', 'AT4', 'Denali', 'Denali Ultimate', 'AT4X'],
  'GMC|SIERRA 2500HD':    ['Pro', 'SLE', 'SLT', 'AT4', 'Denali'],
  'GMC|YUKON':            ['SLE', 'SLT', 'AT4', 'Denali'],
  'GMC|ACADIA':           ['SLE', 'SLT', 'AT4', 'Denali'],
  'GMC|TERRAIN':          ['SLE', 'SLT', 'AT4', 'Denali'],
  'GMC|CANYON':           ['Elevation', 'AT4', 'Denali', 'AT4X'],
  // Dodge / RAM / Jeep / Chrysler
  'DODGE|CHALLENGER':     ['SXT', 'GT', 'R/T', 'R/T Scat Pack', 'SRT 392', 'SRT Hellcat', 'SRT Hellcat Redeye', 'SRT Super Stock', 'Demon 170'],
  'DODGE|CHARGER':        ['SXT', 'GT', 'R/T', 'R/T Scat Pack', 'SRT 392', 'SRT Hellcat', 'SRT Hellcat Redeye', 'SRT Hellcat Jailbreak'],
  'DODGE|DURANGO':        ['SXT', 'GT', 'R/T', 'Citadel', 'SRT 392', 'SRT Hellcat'],
  'DODGE|GRAND CARAVAN':  ['SE', 'SE Plus', 'SXT', 'GT'],
  'RAM|1500':             ['Tradesman', 'Big Horn', 'Lone Star', 'Laramie', 'Sport', 'Rebel', 'Laramie Longhorn', 'Limited', 'TRX'],
  'RAM|2500':             ['Tradesman', 'Big Horn', 'Lone Star', 'Laramie', 'Power Wagon', 'Limited', 'Limited Longhorn'],
  'RAM|3500':             ['Tradesman', 'Big Horn', 'Laramie', 'Limited', 'Limited Longhorn'],
  'JEEP|WRANGLER':        ['Sport', 'Sport S', 'Willys Sport', 'Willys', 'Sahara', 'Sahara Altitude', 'Rubicon', 'Rubicon 392', '4xe', 'High Altitude'],
  'JEEP|GRAND CHEROKEE':  ['Laredo', 'Altitude', 'Limited', 'Overland', 'Summit', 'Trailhawk', 'SRT', 'Trackhawk', '4xe'],
  'JEEP|CHEROKEE':        ['Sport', 'Latitude', 'Latitude Lux', 'Altitude', 'Limited', 'Trailhawk', 'Overland'],
  'JEEP|GLADIATOR':       ['Sport', 'Sport S', 'Willys Sport', 'Willys', 'Overland', 'Rubicon', 'Mojave', 'High Altitude'],
  'JEEP|COMPASS':         ['Sport', 'Latitude', 'Latitude Lux', 'Altitude', 'Limited', 'Trailhawk'],
  // Subaru
  'SUBARU|OUTBACK':       ['Base', 'Premium', 'Limited', 'Limited XT', 'Touring', 'Touring XT', 'Wilderness'],
  'SUBARU|FORESTER':      ['Base', 'Premium', 'Sport', 'Limited', 'Touring', 'Wilderness'],
  'SUBARU|CROSSTREK':     ['Base', 'Premium', 'Sport', 'Limited', 'Wilderness', 'Hybrid'],
  'SUBARU|IMPREZA':       ['Base', 'Premium', 'Sport', 'Limited'],
  'SUBARU|WRX':           ['Base', 'Premium', 'Limited', 'GT', 'STI', 'STI Limited', 'STI S209'],
  'SUBARU|LEGACY':        ['Base', 'Premium', 'Sport', 'Limited', 'Limited XT', 'Touring XT'],
  'SUBARU|ASCENT':        ['Base', 'Premium', 'Limited', 'Touring'],
  'SUBARU|BRZ':           ['Premium', 'Limited'],
  // Nissan
  'NISSAN|ALTIMA':        ['S', 'SR', 'SV', 'SL', 'Platinum', 'Edition One'],
  'NISSAN|ROGUE':         ['S', 'SV', 'SL', 'Platinum', 'Rock Creek'],
  'NISSAN|FRONTIER':      ['King Cab S', 'King Cab SV', 'Crew Cab S', 'Crew Cab SV', 'Crew Cab Pro-4X', 'Crew Cab PRO-X', 'Crew Cab SL'],
  'NISSAN|TITAN':         ['King Cab S', 'King Cab SV', 'Crew Cab S', 'Crew Cab SV', 'Crew Cab Pro-4X', 'Crew Cab SL', 'Crew Cab Platinum Reserve'],
  'NISSAN|PATHFINDER':    ['S', 'SV', 'SL', 'Rock Creek', 'Platinum'],
  'NISSAN|MURANO':        ['S', 'SV', 'SL', 'Platinum'],
  'NISSAN|MAXIMA':        ['S', 'SV', 'SL', 'Platinum'],
  'NISSAN|SENTRA':        ['S', 'SV', 'SR'],
  'NISSAN|ARMADA':        ['S', 'SV', 'SL', 'Platinum'],
  // Hyundai / Kia
  'HYUNDAI|TUCSON':       ['SE', 'SEL', 'N Line', 'XRT', 'Limited', 'Plug-In Hybrid SE', 'Plug-In Hybrid SEL'],
  'HYUNDAI|SANTA FE':     ['SE', 'SEL', 'XRT', 'Limited', 'Calligraphy'],
  'HYUNDAI|ELANTRA':      ['SE', 'SEL', 'N Line', 'Limited', 'N', 'Hybrid Blue', 'Hybrid SEL', 'Hybrid Limited'],
  'HYUNDAI|SONATA':       ['SE', 'SEL', 'SEL Plus', 'N Line', 'Limited', 'Hybrid Blue', 'Hybrid SEL', 'Hybrid Limited'],
  'HYUNDAI|PALISADE':     ['SE', 'SEL', 'XRT', 'Limited', 'Calligraphy'],
  'KIA|SPORTAGE':         ['LX', 'EX', 'S', 'X-Line', 'SX', 'X-Pro', 'SX Prestige', 'Plug-In Hybrid EX', 'Plug-In Hybrid SX'],
  'KIA|SORENTO':          ['LX', 'S', 'EX', 'SX', 'X-Line', 'SX Prestige', 'Plug-In Hybrid EX', 'Plug-In Hybrid SX'],
  'KIA|TELLURIDE':        ['LX', 'S', 'EX', 'SX', 'SX-P', 'X-Line', 'X-Pro', 'X-Pro Prestige'],
  'KIA|FORTE':            ['FE', 'LXS', 'GT-Line', 'EX', 'GT'],
  'KIA|SOUL':             ['LX', 'S', 'EX', 'GT-Line', 'Turbo'],
  // Tesla
  'TESLA|MODEL 3':        ['Standard Range', 'Long Range AWD', 'Performance'],
  'TESLA|MODEL Y':        ['Standard Range', 'Long Range AWD', 'Performance'],
  'TESLA|MODEL S':        ['Long Range', 'Plaid'],
  'TESLA|MODEL X':        ['Long Range', 'Plaid'],
  'TESLA|CYBERTRUCK':     ['AWD', 'Cyberbeast'],
  // Mazda
  'MAZDA|CX-5':           ['Sport', 'Select', 'Preferred', 'Carbon Edition', 'Touring', 'Grand Touring', 'Grand Touring Reserve', 'Signature'],
  'MAZDA|MAZDA3':         ['Select', 'Preferred', 'Premium', 'Premium Plus', '2.5 Turbo'],
  'MAZDA|MX-5 MIATA':     ['Sport', 'Club', 'Grand Touring', 'RF Club', 'RF Grand Touring'],
  // BMW
  'BMW|3 SERIES':         ['330i', '330i xDrive', '330e', '330e xDrive', 'M340i', 'M340i xDrive', 'M3', 'M3 Competition'],
  'BMW|5 SERIES':         ['530i', '530i xDrive', '540i', '540i xDrive', 'M550i', 'M5', 'M5 Competition'],
  'BMW|X3':               ['sDrive30i', 'xDrive30i', 'M40i', 'M'],
  'BMW|X5':               ['sDrive40i', 'xDrive40i', 'xDrive45e', 'M60i', 'M'],
  // Misc
  'LINCOLN|NAVIGATOR':    ['Standard', 'Reserve', 'Black Label'],
  'CADILLAC|ESCALADE':    ['Luxury', 'Premium Luxury', 'Premium Luxury Platinum', 'Sport', 'Sport Platinum', 'V', 'V Blackwing'],
  'PORSCHE|CAYENNE':      ['Base', 'S', 'GTS', 'Turbo', 'Turbo S', 'E-Hybrid', 'Turbo E-Hybrid'],
  'VOLKSWAGEN|JETTA':     ['S', 'Sport', 'SE', 'SEL', 'SEL Premium', 'GLI S', 'GLI Autobahn'],
  'VOLKSWAGEN|TIGUAN':    ['S', 'SE', 'SE R-Line Black', 'SEL', 'SEL R-Line'],
  'ACURA|MDX':            ['Base', 'Technology', 'A-Spec', 'A-Spec Technology', 'Advance', 'Type S', 'Type S Advance'],
  'ACURA|RDX':            ['Base', 'Technology', 'A-Spec', 'A-Spec Technology', 'Advance'],
  'SUBARU|OUTBACK':       ['Base', 'Premium', 'Limited', 'Limited XT', 'Touring', 'Touring XT', 'Wilderness'],
};
